### ISSUE TITLE
Hey Andrey

### ISSUE THREAD

**Issue by bartekus** [keske/Landed#2]
I came upon this repo by an accident but I'm glad that I did since I like your style and I've learn few things while playing with it. I also updated everything and was gonna submit the pull with the updates but then I noticed that on development branch you've already have done so. Bummer since I wanted to use your excellent work as starter for my own homepage but I don't feel right about taking something without giving something back so perhaps if I could help you in some aspects then I'd feel much better about using your work. How could I be of service good sir?

**Comment by keske** [comment]
Hello mate, first of all thank you!

If you want to use this project as starter for your site, don't worry, take it and do it :)

Pay attention that current project was built on this boilerplate https://github.com/anorudes/redux-easy-boilerplate where I'm co-author so I recommend use exactly it for start. Anyway this project and the boilerplate has the same architecture.

Also I updated master brunch with a lot of new features.

**Comment by bartekus** [comment]
The reason why I like the Landed is because coming from script-kiddie-gone-hacker-gone-programmer I have much easier time looking at existing structure to learn way of it's implementation than to stare at blank page and come up with something. The scroller on the first page has given me an insight into a specific problem that I was thinking about as I'm trying to make a simple multistep 'narrow down results/options based on selection' kind of form :)

What are your view on making redux-easy-boilerplate isomorphic?

**Comment by keske** [comment]
Yep, we are working on it and I think in weekend we should done server side rendering, finally :)

**Comment by Bartekus** [comment]
Hey Andrey I've got a proposition that I'd like you and your colleagues to consider as I'd like you all on board of a new open software initiative:
Under Araphel.org, an esoteric conclave would be established to oversight an OSI project called R3Stack (R3Stack.com is the stacks url)

Our main component is currently being finalized by Matt Krick with his Meatier development. 
Basically it's a meteor-like stack build within react-redux-rethinkDB specifications, you can check it out here: https://github.com/mattkrick/meatier

Next we have an very extensive frontend, currently being finalized by OpenCredo as opencredo-react-boilerplate which you can see here: https://github.com/opencredo/opencredo-react-boilerplate

Finally we are in preliminary talks with Alex Pustovalov of the Structor project which we hope to include too as an visual aspect really does aid in teaching children while itself it is not obstructing on weighing in unnecessary in code, you can see here: https://github.com/ipselon/structor

The whole thing will either be entirely docker based as to simplify the installation/operation/deployment or we could utilize AZK as binding agent tho it itself is also docker base so might not be necessary.

The reason for this stack, is to create a framework which unlike other frameworks, do not lend itself to be ridged and unchanging but rather continually evolve with community while providing kids with best practice, always current and reflective of the react community; an full-spectrum solution with emphasis on functional programming. 
Aim is to providing the best structure for learning by allowing kids to look at the current development practices, while at the same time having entire build for reverse engineering purposes as it is my belief that it's the most accessible way for large segment of different potential kids to learn and eventually create and bring into life their own ideas.

By setting an ever evolving standard we can bring balance to the react force and at the same time support the good practices while discarding unwanted ones.

The structure of Araphel.org in a way like that of a philosophical branch of the anonymous movement and itself will be in form of a round table, where each member does his best to express and contribute in whatever capacity they can while at the same time setting an example and nurturing community in general. We will essentially create by hackers for hacker - build-break-learn stack.

What would you say to that?

**Comment by bartekus** [comment]
Thank you for letting me play with your build, I've returned the favor and updated everything up to most current versions. I wasn't entirely sure what you are ultimately after with SmartLoading so I didn't touch it, but that's the last thing that causes any errors. 
Cheer Mate!

**Comment by keske** [comment]
Hello, sorry I didn't give feedback on your last message in this issue because I studied what was in this post. Anyway it seems interesting and could you drop a line on my email hello@andreykeske.com to continue our conversation, of course if you still want.
Thank you!
